In [100]:
import numpy as np
lst1=[1,2,3]
array1 = np.array(lst1)
array1

array([1, 2, 3])

In [101]:
import numpy as np
lst2=[4,5,6]
array2 = np.array(lst2)
array2

array([4, 5, 6])

In [102]:
type(lst1)

list

In [103]:
type(array1)

numpy.ndarray

In [104]:
print("array2 multiplied by array1: ",array1*array2)
print("array2 divided by array1: ",array2/array1)
print("array2 raised to the power of array1: ",array2**array1)

array2 multiplied by array1:  [ 4 10 18]
array2 divided by array1:  [4.  2.5 2. ]
array2 raised to the power of array1:  [  4  25 216]


In [105]:
print("Sine: ",np.sin(array1))
print("Natural logarithm: ",np.log(array1))
print("Base-10 logarithm: ",np.log10(array1))
print("Base-2 logarithm: ",np.log2(array1))
print("Exponential: ",np.exp(array1))

Sine:  [0.84147098 0.90929743 0.14112001]
Natural logarithm:  [0.         0.69314718 1.09861229]
Base-10 logarithm:  [0.         0.30103    0.47712125]
Base-2 logarithm:  [0.        1.        1.5849625]
Exponential:  [ 2.71828183  7.3890561  20.08553692]


In [106]:
list2=[3,2,1]
array2=np.array(list2)
array2

array([3, 2, 1])

In [107]:
print("Adding two numpy arrays {array1} and {array2} together:", array1+array2)

Adding two numpy arrays {array1} and {array2} together: [4 4 4]


In [108]:
print(f"Adding two numpy arrays {array1} and {array2} together:", array1+array2)

Adding two numpy arrays [1 2 3] and [3 2 1] together: [4 4 4]
